CREATE TABLE IF NOT EXISTS $(HangfireConfigurationSchema).configuration(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	connectionstring TEXT,
	schemaname TEXT,
	goalworkercount INTEGER,
	active BOOLEAN,
	name TEXT,
	maxworkersperserver INTEGER
)
WITH (
OIDS=FALSE
);

ALTER TABLE $(HangfireConfigurationSchema).configuration 
	DROP CONSTRAINT IF EXISTS pk_hangfireconfiguration_configuration;
ALTER TABLE $(HangfireConfigurationSchema).configuration  
	ADD CONSTRAINT pk_hangfireconfiguration_configuration PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS $(HangfireConfigurationSchema).keyvaluestore(
	key VARCHAR(100) NOT NULL,
	value TEXT
)
WITH (
OIDS=FALSE
);

ALTER TABLE $(HangfireConfigurationSchema).keyvaluestore
	DROP CONSTRAINT IF EXISTS pk_hangfireconfiguration_keyvaluestore;
ALTER TABLE $(HangfireConfigurationSchema).keyvaluestore
	ADD CONSTRAINT pk_hangfireconfiguration_keyvaluestore PRIMARY KEY (key);
