version: 0.4.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: mssql2017
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    - Hangfire.Configuration.Test
artifacts:
- path: '**\*.nupkg'
  name: NuGet packages
- path: '**\testlog.log'
  name: TestLog
deploy:
#- provider: NuGet
#  api_key:
#    secure:  9C1VMdj5xt4bgCaMPxWCrjCZX/g6HLA1GPNcbSXCqoZ696eM6OYNi5EsetdXWVDk
# after build failure or success
#on_finish:
#- ps: Get-ChildItem .\**\testlog.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  