version: 0.4.{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: 
- mssql2017
- postgresql13
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    - Hangfire.Configuration.Test.dll
    - Hangfire.Configuration.PostgreSql.Test.dll
artifacts:
- path: '**\*.nupkg'
  name: NuGet packages
- path: '**\testlog.log'
  name: TestLog
deploy:
- provider: NuGet
  api_key:
    secure:  6Zd9w9kNtFYawDNct+kHxGmlSNEHXbt+IQ0KKJG8obV8Z0D4KVp0+amJ3QKKCVn3
install:
  - ps: .\postgres-configure-sspi.ps1
# after build failure or success
#on_finish:
#- ps: Get-ChildItem .\**\testlog.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  