version: 0.4.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: mssql2017
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGet packages
deploy:
- provider: NuGet
  api_key:
    secure: BWuVRnqVwKU8i2nJqRw1nRfMCKp4RyPx6peWZgnyDDniNabIWt/kulD1UN6d4+zL