trigger:
- master
name: 1.$(Date:yMM).$(Date:%d).$(Rev:r)
pool:
  name: twfm-devops-vmss
steps:
- template: sql_make_me_admin.yml
- pwsh: |
    Set-Service postgresql-x64-14 -StartupType manual
    Start-Service -Name postgresql-x64-14
- task: UseDotNet@2
  displayName: Install .NET 6 SDK
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    externalFeedCredentials: 'HangfirePro'
- task: DotNetCoreCLI@2
  displayName: Build & test
  inputs:
    command: test
    projects: hangfire.configuration.sln
    arguments: '--configuration release -p:Version=$(Build.BuildNumber) -p:PackageVersion=$(Build.BuildNumber)'
- task: NuGetCommand@2
  displayName: Publish
  inputs:
      command: 'push'
      packagesToPush: 'Hangfire.Configuration/bin/release/*.nupkg'
      feedsToUse: 'select'
      vstsFeed: 'TWFM/twfm'
      publishVstsFeed: 'TWFM/twfm'