# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: twfm-devops

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: test
    projects: hangfire.configuration.sln
    arguments: '--configuration release'
