name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SqlServer
      run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "MSSQL_PID=Standard" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

    - name: Setup PostgreSQL
      run: |
          docker run -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=root -e POSTGRES_DB=envers -p 5432:5432 -d postgres:13

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore -p:Redis=false

    - name: Build
      run: dotnet build --no-restore -p:Redis=false

    - name: Test
      run: dotnet test --no-build --verbosity normal
